In [1]:
#Question That I Want To Answer
# 1. Which Race has the most homeless that has been admitted

In [2]:
# set up
import pandas as pd
hospital_homeless = pd.read_csv('homeless-hospital-encounters-age-race-sex-expected-payer-statewide.csv')
hospital_homeless.head()

,EncounterType,Demographic,DemographicValue,Year,Homeless,All
0,IP,AGEGROUP,0 to 18,2019-2020,"1,986","1,263,963"
1,IP,AGEGROUP,19 to 39,2019-2020,"77,675","1,567,051"
2,IP,AGEGROUP,40 to 59,2019-2020,"106,805","1,305,536"
3,IP,AGEGROUP,60+,2019-2020,"50,972","2,897,381"
4,IP,RACEGROUP,American Indian/Alaska Native,2019-2020,"1,744","27,019"

In [3]:
# more info about this dataset
hospital_homeless.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EncounterType     34 non-null     object
 1   Demographic       34 non-null     object
 2   DemographicValue  34 non-null     object
 3   Year              34 non-null     object
 4   Homeless          34 non-null     object
 5   All               34 non-null     object
dtypes: object(6)
memory usage: 1.7+ KB

In [4]:
# need to change the data type for homeless and all from objects to ints
hospital_homeless['Homeless'] = hospital_homeless['Homeless'].str.replace(pat = ',', repl = '', regex = False)
hospital_homeless['All'] = hospital_homeless['All'].str.replace(pat = ',', repl = '', regex = False)
hospital_homeless[['Homeless', 'All']] = hospital_homeless[['Homeless', 'All']].astype('int64')
hospital_homeless.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EncounterType     34 non-null     object
 1   Demographic       34 non-null     object
 2   DemographicValue  34 non-null     object
 3   Year              34 non-null     object
 4   Homeless          34 non-null     int64
 5   All               34 non-null     int64
dtypes: int64(2), object(4)
memory usage: 1.7+ KB

In [5]:
#Full Cleaned DataSet
hospital_homeless

,EncounterType,Demographic,DemographicValue,Year,Homeless,All
0,IP,AGEGROUP,0 to 18,2019-2020,1986,1263963
1,IP,AGEGROUP,19 to 39,2019-2020,77675,1567051
2,IP,AGEGROUP,40 to 59,2019-2020,106805,1305536
3,IP,AGEGROUP,60+,2019-2020,50972,2897381
4,IP,RACEGROUP,American Indian/Alaska Native,2019-2020,1744,27019
5,IP,RACEGROUP,Asian/Pacific Islander,2019-2020,5494,703785
6,IP,RACEGROUP,Black,2019-2020,46546,562091
7,IP,RACEGROUP,Hispanic,2019-2020,59064,2310708
8,IP,RACEGROUP,Other Race/Ethnicity,2019-2020,17265,471747
9,IP,RACEGROUP,White,2019-2020,107428,2958841
10,IP,SEX,Female,2019-2020,67020,3922100
11,IP,SEX,Male,2019-2020,170489,3111590
12,IP,PAYER,Medi-Cal,2019-2020,152816,2119419
13,IP,PAYER,Medicare,2019-2020,48658,2463316
14,IP,PAYER,Other Payer,2019-2020,8406,215789
15,IP,PAYER,Private Coverage,2019-2020,12486,2067829
16,IP,PAYER,Uninsured,2019-2020,15175,167838
17,ED,AGEGROUP,0 to 18,2019-2020,6280,4642761
18,ED,AGEGROUP,19 to 39,2019-2020,251589,7224829
19,ED,AGEGROUP,40 to 59,2019-2020,290589,5314602
20,ED,AGEGROUP,60+,2019-2020,109490,5029232
21,ED,RACEGROUP,American Indian/Alaska Native,2019-2020,3684,76224
22,ED,RACEGROUP,Asian/Pacific Islander,2019-2020,11411,1392154
23,ED,RACEGROUP,Black,2019-2020,153156,2322766
24,ED,RACEGROUP,Hispanic,2019-2020,148944,9264900
25,ED,RACEGROUP,Other Race/Ethnicity,2019-2020,47640,1405758
26,ED,RACEGROUP,White,2019-2020,293809,7750715
27,ED,SEX,Female,2019-2020,189289,12077962
28,ED,SEX,Male,2019-2020,469166,10132998
29,ED,PAYER,Medi-Cal,2019-2020,421929,9365162
30,ED,PAYER,Medicare,2019-2020,106465,4281073
31,ED,PAYER,Other Payer,2019-2020,19700,747537
32,ED,PAYER,Private Coverage,2019-2020,26271,6268051
33,ED,PAYER,Uninsured,2019-2020,84279,1550694

In [6]:
# Based on Race who has the most homeless
#Boolaen Mask
races =  (hospital_homeless['Demographic'] == 'RACEGROUP')
#Seperate DataFrame
races_hospital = hospital_homeless[races]
races_hospital = races_hospital.reset_index()
races_hospital = races_hospital.drop(labels = ['index'], axis = 1)

races_hospital.head()

,EncounterType,Demographic,DemographicValue,Year,Homeless,All
0,IP,RACEGROUP,American Indian/Alaska Native,2019-2020,1744,27019
1,IP,RACEGROUP,Asian/Pacific Islander,2019-2020,5494,703785
2,IP,RACEGROUP,Black,2019-2020,46546,562091
3,IP,RACEGROUP,Hispanic,2019-2020,59064,2310708
4,IP,RACEGROUP,Other Race/Ethnicity,2019-2020,17265,471747

In [7]:
#Based on Race who has the most homeless hospitalized
#Looking at the max and mean
races_hospital.groupby('DemographicValue').agg({'Homeless':['mean', 'max',]})

                               Homeless
                                   mean     max
DemographicValue
American Indian/Alaska Native    2714.0    3684
Asian/Pacific Islander           8452.5   11411
Black                           99851.0  153156
Hispanic                       104004.0  148944
Other Race/Ethnicity            32452.5   47640
White                          200618.5  293809

In [8]:
#Based on Race who has the most homeless hospitalized
#Looking at the percents based on Homeless and All
total_all = races_hospital['Homeless'].sum()
All_Race = (races_hospital['Homeless'] / total_all) * 100
All_Race.head()

0    0.194603
1    0.613043
2    5.193794
3    6.590604
4    1.926500
Name: Homeless, dtype: float64

In [9]:
races_hospital['Homeless Admitted Percentage'] = All_Race
races_hospital = races_hospital.sort_values(by = 'Homeless Admitted Percentage', ascending = False)
races_hospital.head()

,EncounterType,Demographic,DemographicValue,Year,Homeless,All,Homeless Admitted Percentage
11,ED,RACEGROUP,White,2019-2020,293809,7750715,32.784414
8,ED,RACEGROUP,Black,2019-2020,153156,2322766,17.089775
9,ED,RACEGROUP,Hispanic,2019-2020,148944,9264900,16.619783
5,IP,RACEGROUP,White,2019-2020,107428,2958841,11.987257
3,IP,RACEGROUP,Hispanic,2019-2020,59064,2310708,6.590604

In [10]:
#Summary: 
'''
Based off the data we are able to suggest that the race that is mostly admitted solely based on race is gonna be White
'''

'\nBased off the data we are able to suggest that the race that is mostly admitted solely based on race is gonna be White\n'